server:
  port: 8081

spring:
  application:
    name: webApp

    thymeleaf:
      prefix: classpath:src/main/resources/templates
      suffix: .html
      mode: HTML
      enabled: false
      encoding: UTF-8